Repository FRONTENDBOOTCAMP-13th/samsix, pull requests merged in 2025-03, with the labels that each got.

#16 Modify: 비밀번호 숨김/보임 아이콘 수정 완료.
  src/assets/login/PW unvisible icon.svg
  src/assets/login/PW visible icon.svg
  src/components/loginpage_components.html
  src/pages/login_page.html
Labels: 💫 Style, ⭐ HTML, 🔧 feature

#19 Design: 메인 페이지 - 실시간 인기 프로그램 컴포넌트
  src/assets/poster/popular_programs/Canada_checkin_lg.png
  src/assets/poster/popular_programs/Canada_checkin_md.png
  src/assets/poster/popular_programs/Canada_checkin_sm.png
  src/assets/poster/popular_programs/Saturday_lg.png
  src/assets/poster/popular_programs/Saturday_md.png
  src/assets/poster/popular_programs/Saturday_sm.png
  src/assets/poster/popular_programs/Show_me_the_money_lg.png
  src/assets/poster/popular_programs/Show_me_the_money_md.png
  src/assets/poster/popular_programs/Show_me_the_money_sm.png
  src/assets/poster/popular_programs/chaebol_son_lg.png
  src/assets/poster/popular_programs/chaebol_son_md.png
  src/assets/poster/popular_programs/chaebol_son_sm.png
  src/assets/poster/popular_programs/drunk_urban_women_lg.png
  src/assets/poster/popular_programs/drunk_urban_women_md.png
  src/assets/poster/popular_programs/drunk_urban_women_sm.png
  src/assets/poster/popular_programs/love_catcher_lg.png
  src/assets/poster/popular_programs/love_catcher_md.png
  src/assets/poster/popular_programs/love_catcher_sm.png
  src/assets/poster/popular_programs/twilight_lg.png
  src/assets/poster/popular_programs/twilight_md.png
  src/assets/poster/popular_programs/twilight_sm.png
  src/assets/poster/popular_programs/useful_job_lg.png
  src/assets/poster/popular_programs/useful_job_md.png
  src/assets/poster/popular_programs/useful_job_sm.png
  src/components/main_card.html
  src/components/main_card_components.html
  src/pages/main_page.html
  src/rename.py
  src/style.css
Labels: 💫 Style, ⭐ HTML, 🟡 Priority: Medium, 🔧 feature

#41 Refactor: 로그인 페이지
  src/assets/login/taing_logo.svg
  src/assets/login/unvisible_pwicon.svg
  src/assets/login/visible_pwicon.svg
  src/components/findid_components.html
  src/components/findpw_components.html
  src/components/loginpage_components.html
  src/pages/findid_page.html
  src/pages/findpw_page.html
  src/pages/login_page.html
Labels: 🧰 Refactoring

#42 Refactor: 메인 페이지 리팩토링
  src/assets/icon/taing_logo.svg
  src/assets/poster/only/Universal_lg.png
  src/assets/poster/only/Universal_md.png
  src/assets/poster/only/Universal_sm.png
  src/assets/poster/only/drunk_urban_women_lg.png
  src/assets/poster/only/drunk_urban_women_md.png
  src/assets/poster/only/drunk_urban_women_sm.png
  src/assets/poster/only/food_chronicle_lg.png
  src/assets/poster/only/food_chronicle_md.png
  src/assets/poster/only/food_chronicle_sm.png
  src/assets/poster/only/love_catcher_lg.png
  src/assets/poster/only/love_catcher_md.png
  src/assets/poster/only/love_catcher_sm.png
  src/assets/poster/only/ransom_lg.png
  src/assets/poster/only/ransom_md.png
  src/assets/poster/only/ransom_sm.png
  src/assets/poster/only/strange_lg.png
  src/assets/poster/only/strange_md.png
  src/assets/poster/only/strange_sm.png
  src/assets/poster/only/transfer_love_lg.png
  src/assets/poster/only/transfer_love_md.png
  src/assets/poster/only/transfer_love_sm.png
  src/components/main_card_components.html
  src/components/main_swiper_auto.html
  src/main.js
  src/pages/main_page.html
  src/style.css
Labels: 🐛 BugFix, 🧰 Refactoring

#43 Refactor: 프로필 페이지 리팩토링
  src/components/01_profile_head.html
  src/components/02_profile_content.html
Labels: 🧰 Refactoring

#45 Design: 프로필 컴포넌트 조립
  src/pages/profile_page.html
Labels: 💫 Style, ⭐ HTML

#44 Feat: 회원가입 페이지
  src/assets/login/check-red.svg
  src/components/findid_components.html
  src/components/findpw_components.html
  src/components/loginpage_components.html
  src/components/register_components.html
  src/pages/findid_page.html
  src/pages/findpw_page.html
  src/pages/login_page.html
  src/pages/register_page.html
Labels: 💫 Style, ⭐ HTML, ✨ Javascript, 🔧 feature

#50 Design: 모달 컴포넌트 제작
  src/components/loginpage_components.html
  src/components/modal_components.html
  src/main.js
  src/pages/login_page.html
  src/style.css
Labels: 💫 Style, ⭐ HTML, ✨ Javascript

#58 Refactor: 메인 페이지 및 랜딩 페이지 리팩토링
  src/assets/banner/gradation_img_lg.png
  src/assets/banner/gradation_img_md.png
  src/assets/banner/gradation_img_sm.png
  src/components/main/modal_components.html
  src/main.js
  src/pages/landing_page.html
  src/pages/main_page.html
  src/style.css
Labels: 🧰 Refactoring

#60 Refactor: 검색 컴포넌트 리팩토링 및 컴포넌트 조립
  src/components/search/01_search_head.html
  src/components/search/02_search_searchbar.html
  src/components/search/03_search_popular.html
  src/main.js
  src/pages/search_page.html
  src/style.css
Labels: 💫 Style, 🧰 Refactoring

#61 Refactor: 로그인, ID 찾기, PW 찾기, 회원가입 페이지
  src/main.js
  src/pages/findid_page.html
  src/pages/findpw_page.html
  src/pages/login_page.html
  src/pages/register_page.html
  src/style.css
Labels: 🧰 Refactoring

#69 Modify: 스와이퍼 배너 js로 수정
  src/assets/banner/Black_Salt_Dragon.webp
  src/assets/banner/Couple_Palace2.webp
  src/assets/banner/Harry_Potter.webp
  src/assets/banner/divorce_insurance.webp
  src/assets/icon/taing_only.svg
  src/assets/title/Black_Salt_Dragon.webp
  src/assets/title/Couple_Palace2.webp
  src/assets/title/Harry_Potter.webp
  src/assets/title/divorce_insurance.webp
  src/components/landing/landing_modal.html
  src/components/main/main_banner.html
  src/main.js
  src/pages/main_page.html
  src/style.css
Labels: 💫 Style, ⭐ HTML, ✨ Javascript, 🔧 feature

#70 Feat/search : 메인페이지에 검색모달창 구현 초기디자인
  src/main.js
  src/pages/main_page.html
  src/pages/profile_page.html
Labels: 💫 Style

#71 Refactor: 숨김/보임 아이콘
  public/login/loginpw_invisible.svg
  public/login/loginpw_visible.svg
  src/assets/login/loginpw_invisible.svg
  src/assets/login/loginpw_visible.svg
  src/js/toggle_password.js
  src/main.js
  src/pages/login_page.html
  src/pages/register_page.html
Labels: 🐛 BugFix

#73 Chore: js 파일 분리
  src/js/main_page.js
  src/main.js
  src/pages/main_page.html
Labels: 🐛 BugFix, ✨ Javascript

#74 Modify: 검색 페이지 js파일 분리
  src/js/search_page.js
Labels: ✨ Javascript, 🧰 Refactoring

#75 자바스크립트 파일 분리
  src/js/login_page.js
  src/js/toggle_password.js
Labels: ✨ Javascript

#78 feat: js 분리2
  src/js/login_page.js
Labels: ✨ Javascript

#86 Design: 랜딩 페이지 모달 구현
  src/components/landing/landing_modal.html
  src/css/landing_page.css
  src/css/main_page.css
  src/pages/landing_page.html
  src/pages/main_page.html
  src/style.css
Labels: 💫 Style, ⭐ HTML, ✨ Javascript

#92 Docs: README 수정
  README.md
Labels: 📖 Documentation

#94 Design: 검색모달창 구현
  src/css/search_page.css
  src/js/main_page.js
  src/js/search_page.js
  src/pages/main_page.html
Labels: ⭐ HTML, ✨ Javascript, 🔧 feature

#93 Design: index 스타일링
  index.html
  src/components/login/modal_components.html
  src/components/main/modal.html
Labels: 📖 Documentation, 💫 Style, ⭐ HTML

#100 Refactor: 메인 페이지 및 랜딩 페이지 리팩토링
  index.html
  src/components/landing/landing_banner.html
  src/components/landing/landing_card_1set.html
  src/components/landing/landing_card_2sets.html
  src/components/landing/landing_modal.html
  src/components/landing/landing_side.html
  src/components/main/main_banner.html
  src/components/main/main_card.html
  src/components/main/main_card_components.html
  src/components/main/main_menu.html
  src/components/main/main_navigation.html
  src/components/main/main_swiper.html
  src/components/main/main_swiper_auto.html
  src/components/main/modal.html
  src/css/landing_page.css
  src/js/main_page.js
  src/pages/landing_page.html
  src/pages/main_page.html
Labels: 🐛 BugFix, 🧰 Refactoring

#101 Refactor: 로그인 관련 전체 페이지
  index.html
  public/taing.svg
  src/components/login/login_description.html
  src/components/login/login_footer.html
  src/components/login/login_form.html
  src/components/login/login_header.html
  src/components/login/modal_components.html
  src/css/login.css
  src/js/login_page.js
  src/pages/findid_page.html
  src/pages/findpw_page.html
  src/pages/login_page.html
  src/pages/register_page.html
Labels: 🧰 Refactoring

#102 Feat/profile refact
  index.html
  src/components/profile/02_profile_content.html
  src/css/main_page.css
  src/css/profile_page.css
  src/js/profile_page.js
  src/pages/main_page.html
  src/pages/profile_page.html
Labels: 🧰 Refactoring

#104 Feat: 로그아웃 모달 적용
  src/css/main_page.css
  src/js/main_page.js
  src/pages/main_page.html
Labels: 💫 Style, ⭐ HTML, ✨ Javascript

#108 Design: 애니메이션 구현
  src/components/main/main_animation.html
  src/css/landing_page.css
  src/js/main_page.js
  src/pages/landing_page.html
  src/pages/main_page.html
Labels: 💫 Style, ⭐ HTML, ✨ Javascript

#109 Design: 로그인페이지의 fadeIn 애니메이션 -> 프로필, 메인 페이지에 적용
  src/css/main_page.css
  src/css/profile_page.css
  src/pages/main_page.html
  src/pages/profile_page.html
Labels: 💫 Style

#110 Chore: favicon 교체
  src/components/landing/landing_banner.html
  src/components/landing/landing_card_1set.html
  src/components/landing/landing_card_2sets.html
  src/components/landing/landing_modal.html
  src/components/landing/landing_side.html
  src/components/login/login_description.html
  src/components/login/login_footer.html
  src/components/login/login_form.html
  src/components/login/login_header.html
  src/components/login/modal_components.html
  src/components/main/main_animation.html
  src/components/main/main_banner.html
  src/components/main/main_card.html
  src/components/main/main_menu.html
  src/components/main/main_navigation.html
  src/components/main/modal.html
  src/components/profile/01_profile_head.html
  src/components/profile/02_profile_content.html
  src/components/profile/03_profile_footer.html
  src/components/search/01_search_head.html
  src/components/search/02_search_searchbar.html
  src/components/search/03_search_popular.html
  src/pages/findid_page.html
  src/pages/findpw_page.html
  src/pages/landing_page.html
  src/pages/login_page.html
  src/pages/main_page.html
  src/pages/profile_page.html
  src/pages/register_page.html
  src/pages/search_page.html
Labels: 💫 Style, ⭐ HTML

#111 BugFix: 프로필 페이지 이미지 오류 해결
  index.html
  src/css/main_page.css
  src/js/main_page.js
  src/js/search_page.js
  src/pages/main_page.html
  src/pages/profile_page.html
Labels: 🐛 BugFix

#112 Design: 로그인 페이지 - 헤더 통일하기
  src/pages/login_page.html
Labels: 💫 Style

#113 Design: index 페이지 스타일링
  index.html
  test.html
Labels: 📖 Documentation, 💫 Style

#114 Modify: header
  README.md
  src/pages/findid_page.html
  src/pages/findpw_page.html
  src/pages/register_page.html
Labels: 💫 Style, ⭐ HTML

#120 Refactor: 로그인 관련 페이지
  src/components/login/login_footer.html
  src/components/login/login_form.html
  src/components/login/login_header.html
  src/components/login/modal_components.html
  src/pages/findid_page.html
  src/pages/findpw_page.html
  src/pages/login_page.html
  src/pages/main_page.html
  src/pages/register_page.html
Labels: 🐛 BugFix, 🧰 Refactoring

#121 Modify: 프로필/검색 페이지 - validate local HTML 수정
  src/pages/profile_page.html
  src/pages/search_page.html
Labels: 🐛 BugFix, ⭐ HTML

#123 Design: index 페이지에 삼식이 추가
  index.html
  public/samsix.png
Labels: 💫 Style
